version: "3.9"

services:
  web-shop-tomify:
    container_name: web-shop-tomify
    build:
      context: .
      dockerfile: Dockerfile-deploy
    ports:
      - "${OUTWARD_PORT:-80}:80"
    networks:
      - frontend_backend # Exists already on server

networks:
  frontend_backend:
    external: true