version: "3.9"

services:
  web-shop-tomify:
    container_name: web-shop-tomify
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "${OUTWARD_PORT:-80}:80"
    networks:
      - inter_server_connection

networks:
  inter_server_connection:
    external: true