FROM nginx:1.21.0-alpine as production
# Copy built assets from builder
COPY ./build /usr/share/nginx/html
COPY nginx-deploy.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]