version: "3.9"

services:
  web-shop-tomify:
    container_name: web-shop-tomify
    build: .
    ports:
      - "${OUTWARD_PORT:-80}:80"
    networks:
      - musicshopbackend_musicshop_backend

networks:
  musicshopbackend_musicshop_backend:
    external: true